import Head from "next/head";
import Layout from "./layout";
import { getSortedPostsData } from "../lib/posts";
import { redirect } from "next/dist/server/api-utils";
import Link from "next/link";
import Date from "../components/date";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  console.log(allPostsData);
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {
  return (
    <div className="h-full bg-silver-tree-100">
      <Head>
        <title>Tianci: Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full p-10">
        <Layout>
          <section className="">
            <div className=" flex flex-cols p-10">
              <div className="notes-date basis-1/4 bg-silver-tree-200 h-96 rounded">
                Blogs
              </div>
              <ul className="notes-content basis-3/4 bg-silver-tree-200 font-blog rounded-xl">
                {allPostsData.map((elem) => (
                  <li className="p-2" key={elem.id}>
                    <Link href={`/posts/${elem.id}`}>{elem.title}</Link>
                    <br />
                    <small className="">
                      <Date dateString={elem.date} />
                    </small>
                    <br />
                    <br />
                  </li>
                ))}
              </ul>
            </div>
          </section>
        </Layout>
      </main>
    </div>
  );
}
