import Head from 'next/head'
import Layout from './layout'
import { useState } from 'react'

export default function Home() {

  return (
    <div className='h-full'>
      <Head>
        <title>Tianci: Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main className="h-screen">
        <Layout>
          <h2 className="p-5 font-blog text-2xl text-center">Talk to me: </h2>
          <div className="text-xl text-center">
            <a href="tianci@iggee.dev">tianci@iggee.dev</a>
            <br></br>
            <a href="https://github.com/iggeehu" className="icon github" title="GitHub">
              GitHub
            </a>
            <br></br>
            <a href="https://www.linkedin.com/in/iggee" className="icon linkedin" title="LinkedIn"> 
              LinkedIn
            </a>s
           
            
          </div>
        </Layout>
      </main>
    </div>
  )
}
