import Head from 'next/head'
import dynamic from 'next/dynamic'
import Layout from './layout'
import react from 'react'
import { useState } from 'react'



export default function Home() {

  const [showTxt, setShowTxt] = useState(true)

  const hellotxtButton = () => {
    if(showTxt)
    {
      return(
        <div className="basis-1/5 font-cyber p-3 rounded text-5xl bg-silver-tree-400 cursor-default" onClick={()=>{setShowTxt(true)}}> 
                  <p className="text-center">Hello.txt</p> 
                </div>)
    }
    else{
      return(
        <div className="basis-1/5 font-cyber p-3 rounded text-5xl bg-inherit hover:bg-silver-tree-300 cursor-default" onClick={()=>{setShowTxt(true)}}> 
        <p className="text-center">Hello.txt</p> 
      </div>)
    }
  }

  const hellojavaButton = () => {
    if(!showTxt)
    {
      return(
        <div className="basis-2/5 font-cyber p-3 rounded text-5xl bg-silver-tree-400 cursor-default" onClick={()=>{setShowTxt(false)}}>
                <p className="text-center">Hello.java</p>
              </div>
            )
    }
    else{
      return(
        <div className="basis-1/5 font-cyber p-3 rounded text-5xl bg-inherit hover:bg-silver-tree-300 cursor-default" onClick={()=>{setShowTxt(false)}}> 
        <p className="text-center">Hello.java</p> 
      </div>)
    }
  }

  const hellotxt = () => {
    return(
    <div className="Hello.txt p-5">
            <p className='font-cyber'>Welcome to my page! My name is Tianci Hu Marrero (Iggee) and I am a software developer.
            <br></br>
            <br></br>
            I am a Chinese mainlander and I recently moved to the U.S. with my family. During the 1.5 of immigration flux 
            (translate: moving 3 dogs and a dozen boxes to the U.S., finding a place to rent,
            waiting for the work permit, etc), I started teaching myself computer science.
            <br></br>
            <br></br>
            I started with the classic MERN stack. The beauty of self-teaching is that eventually, you 
            get fast at learning new techs (learned next.js for this portfolio site, kind of an overkill but fun). 
            I have written python data projects employing MySQL and pandas. I have 
            written an OOP-style clone of Space Invaders in Java. I have also dabbled with OS scheduling & locking 
            in C.
            <br></br>
            <br></br>
            Currently, my interests are in lower-level fundamentals because I found that knowing these things always helped me be a better programmer. 
            <br></br>
            <br></br>
            Previously, I worked as a full-time interpreter/translator and technical writer. I also briefly worked a video producer
            for a Beijing startup. 
            <br></br>
            <br></br>
            In my free time I like dancing salsa, lifting weights, and reading. 
            <br></br>
            <br></br>
            </p>
            <p className='font-cyber'>This site is used to demonstrate my projects and store my studynotes.</p>
          </div>)
  }

  const hellojava = () => {
    const ReactEmbedGist = dynamic(() => import("react-embed-gist"), {
      ssr: false,
  });
    return(
      <div className="Hello.java p-10">
          <ReactEmbedGist gist="iggeehu/6e8f094289c26e00029d4598e603cc2c" />
      </div>
    )
  }


  return (
    <div className='h-full bg-silver-tree-100'>
      <Head>
        <title>Tianci Hu Marrero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main className="h-screen">
        <Layout>
          <div className="index-body p-20">
            <div className="index-title flex flex-row items-center">
              <div>{hellotxtButton()}</div>
              <div>{hellojavaButton()}</div>
            </div>
            <div className="index-content flex bg-silver-tree-400">
              {!showTxt? hellojava(): hellotxt()}
            </div>
          </div>
        </Layout>
      </main>
    </div>
  )
}
