import Head from "next/head";
import dynamic from "next/dynamic";
import Layout from "./layout";
import react from "react";
import { useState } from "react";

export default function Home() {
  return (
    <div className="h-full">
      <Head>
        <title>Tianci Hu Marrero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="p-10 bg-silver-tree-100">
        <Layout>
          <div className="index-body md:p-20 lg:p-20 sm:p-1">
            <div className="index-title flex flex-row items-center">
              <span>
                <h1 className="text-center text-2xl font-bold">
                  Tianci Hu Marrero
                </h1>
                <br />
                <h2 className="text-center text-xl font-bold"> ~ About Me ~</h2>
                <br />
                <p className="text-center text-l">
                  I am a multilingual translator turned full-stack programmer.
                  In my past career, I travelled around Asia, published
                  translations of classic literary works, coached & evaluated
                  other translators. I discovered programming because I wanted
                  to automate my translation workflow without paying hundreds of
                  dollars. Before I knew it I was spending entire evenings
                  learning programming. Software engineering has allowed me to
                  solve thorny, murky problems that I could not approach before.
                  It also helped me become a more detail-oriented and persistent
                  person. I like clean and extensible code. I like test-driven
                  development and well-documented workflows.
                </p>
                <br />
                <h2 className="text-center text-xl font-bold">~ Education ~</h2>
                <br />
                <h3 className="text-center text-l font-bold">
                  B.A in Russian and French Literature, Kenyon College (GPA 3.5)
                </h3>
                <br />
                <h3 className="text-center text-l font-bold">
                  My DIY Cost-Nothing Computer Science Degree:
                </h3>
                <br />
                <p className="text-center text-l">
                  I chose not to receive a formal education in Computer Science
                  because I enjoy imposing discipline and structure on myself
                  without external presence. Below is my completely
                  internet-sourced curriculum:
                </p>
                <br />
                <div className="grid justify-items-center text-l">
                  <a
                    className="hover:underline"
                    href="https://pll.harvard.edu/course/cs50-introduction-computer-science?delta=0"
                  >
                    CS050 Harvard Intro To Computer Science
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://www.freecodecamp.org/learn/2022/responsive-web-design/"
                  >
                    CS110 Web Musketeers: Html, CSS, Javascript
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://www.freecodecamp.org/learn/front-end-development-libraries/"
                  >
                    CS150 React, Redux, and NextJS
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://immigence.herokuapp.com/"
                  >
                    CS170 Python and Data Visualizations
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://nostarch.com/howlinuxworks3"
                  >
                    CS180 Linux and Bash Basics
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://pages.cs.wisc.edu/~remzi/OSTEP/"
                  >
                    CS210 Basics Of Operating Systems
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://www.udemy.com/course/java-the-complete-java-developer-course/"
                  >
                    CS230 Java Programming
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://leetcode.com/iggeehu/"
                  >
                    CS250 Intermediate Data Structures
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://www.nand2tetris.org/"
                  >
                    CS270 Hardware, Computer Architecture, Compilers
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://dataintensive.net/"
                  >
                    CS300 Distributed Systems in Theory
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://fly.io/blog/gossip-glomers/"
                  >
                    CS340 Distributed Systems in Practice
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://protohackers.com/"
                  >
                    CS310 Networking Protocols
                  </a>
                  <br />
                  <a
                    className="hover:underline"
                    href="https://lwn.net/Kernel/LDD3/"
                  >
                    CS380 Linux Device Drivers
                  </a>
                </div>
                <br />
                <br />
                <h2 className="text-center text-xl font-bold">
                  ~ Projects & Open Source Contribs{" "}~
                </h2> <br />
                <table className="text-l border">
                  <tr className="border">
                    <td className="font-bold">Name</td>
                    <td className="font-bold">Description</td>
                    <td className="font-bold">Tech/tools</td>
                  </tr>
                  <tr className="border">
                    <td className="font-bold p-3">
                      <a href="https://python-rq.org/">Redis Queue</a>
                    </td>
                    <td>
                      Revamped old documentation; added commandline monitoring
                      features.
                    </td>
                    <td>Python &amp; Pytest</td>
                  </tr>
                  <tr className="border">
                    <td className="font-bold p-3">Immigence</td>
                    <td>
                      A data service site that takes user request and present
                      immigration data visualizations per case range. The data
                      is collected with my own automated daily scraping bots.
                    </td>
                    <td>Flask, Matplotlib, Bokeh, Redis, AWS RDS &amp; EC2</td>
                  </tr>
                  <tr className="border">
                    <td className="font-bold p-3">BookList</td>
                    <td>
                      A Social Media site (in beta) for book enthusiasts. Users
                      can compile reading lists, share and collect others&#39;
                      list, and one-click add a whole list to cart on
                      AbeBooks.com.
                    </td>
                    <td>React, Redux, Node, MongoDB</td>
                  </tr>
                </table>
                <br />
                <br />
                <h2 className="text-center text-xl font-bold">
                  ~ Work Experience ~
                </h2>
                <h3 className="font-bold text-l">Programmer Fellow</h3>
                Recurse Center (March - June, 2023) 
                <br/>
                Recurse Center is a
                selective retreat for curious programmers to explore their
                intellectual interests and collaborate. <br />
                - Wrote toy Assemblers &
                Compilers, and Operating Systems. <br />
                - Studied Censorship Resistant
                Network Protocols & Data-intensive Application Design. <br />
                - Created
                a Django Chat App with Chat GPT integration with batchmates.
                <br /><br />

                <h3 className="font-bold text-l">Translator & Technical Writer</h3>
                Self-Employed (December 2016 - February 2023) <br />
                - Transcreated
                API-documentation from Chinese to English for English-speaking
                developers. <br />
                - Created marketing copies and documentation for CRM
                software vendors and fintech products. <br />
                - Published Christian
                Anderson Fairytales and Mary Karr's "The Liars Club" in Chinese. <br />
                -
                “Translating For Tech” trainer for Proz.com, world’s biggest
                translators’ marketplace. <br />
                <br />
                <h2 className="text-center text-xl font-bold">~ Skills ~</h2> <br />
                <h3 className="text-center font-bold">Test-driven Development</h3>
                Either in actual test code or a big markdown file, I always
                write down things that could go wrong with the code before I
                start coding. Handling exceptions and testing are an often
                overlooked part of software development, especially in an agile
                environment when sometimes things need to go fast. However, good
                software cannot survive long without a good test suite!
                Currently, I am familiar with testing frameworks such as Jest,
                Mocha, PyTest, and JUnit. <br /><br />
                <h3 className="text-center font-bold">Formalities & Due Diligence</h3>
                Formatting matters to me. Consistent naming conventions matter
                to me. Committing everything to paper and keeping a record of
                decision-making matter to me. These things might not seem
                significant at the moment, but could ball up into head-splitting
                complexities later. <br /><br />
                <h3 className="text-center font-bold">Collaborate & Communicate</h3>I believe in
                saying exactly what I mean while remaining civil & open. Years
                of running my own business and doing customer support has helped
                me hone the skills of simple, effective, and genuine
                communication. Also, I enjoy collaboration and comraderie among
                collaborators. I never hold a narrow-minded competition mindset.
                I love learning from others and helping others learn to the best
                of my abilities. <br /><br />
                <h3 className="text-center font-bold">Autonomy</h3>I am highly autonomous and good
                at finding answers on my own. I can pick myself up to speed when
                help is not too available.
                <br />
                <br />
                <br />
                <h2 className="text-center text-xl font-bold">~ Hobbies ~</h2>
                <p>When I am not coding, I am spending time with my Son and reading
                my Kindle.</p>
                <br />I love cooking, salsa dancing, and learning foreign languages. <br />
                <br />As a resident of Flushing, NY, I really love my neighborhood and have taken
                countless walks around. I love observing the seasons changing and noticing recurring
                characters in the neighborhood. 
              </span>
            </div>
          </div>
        </Layout>
      </main>
    </div>
  );
}
