import Head from 'next/head'
import Layout from './layout'
import { useState } from 'react'
import Immigence from './projects/Immigence'
import BookList from './projects/BookList'

export default function Home() {

  const [showRecurse, setShowRecurse] = useState(false)  

  return (
    <div className='h-full bg-silver-tree-100'>
      <Head>
        <title>Tianci: Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main className="h-screen">
        <Layout>
          <h2 className="p-5 font-blog text-2xl text-center">Projects Showcase</h2>
          <div className="projects-body p-10 grid lg:grid-cols-3 md:grid-cols-3 sm:grid-cols-1">
            
            <div className="project-child font-blog rounded">
            <Immigence />
            </div>

            <div className="project-child font-blog rounded">
            <BookList />
            </div>
            

            
          </div>
        </Layout>
      </main>
    </div>
  )
}
