import Head from 'next/head'
import Layout from './layout'
import { useState } from 'react'
import RecurseCenter from './notes/RecurseCenter'
import OsNotes from './notes/OsNotes'



export default function Home() {

  const [showRecurse, setShowRecurse] = useState(false)
  const [showOS, setShowOS] = useState(false)
  const [showMisc, setShowMisc] = useState(false)

  const showRecurseComponent = () => {
    if(showRecurse){return <RecurseCenter />}
  }

  const showOSComponent = () => {
    if(showOS){return <OsNotes />}
  }

  const showMiscComponent = () => {
    if(showMisc){return <OsNotes />}
  }

  return (
    <div className='h-full bg-silver-tree-100'>
      <Head>
        <title>Tianci: Notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main className="h-screen">
        <Layout>
          <div className="index-body p-20">
            
            <div className="blog-subcategory font-blog text-2xl flex hover:text-silver-tree-400 cursor-default"
            onClick={()=>setShowRecurse(!showRecurse)}
            >
            Recurse Center Log
            </div>
            {showRecurseComponent()}

            <div className="blog-subcategory font-blog text-2xl flex hover:text-silver-tree-400  cursor-default"
            onClick={()=>setShowOS(!showOS)}
            >
            Operating Systm Study Notes
            </div>
            {showOSComponent()}
            <div className="blog-subcategory font-blog text-2xl flex hover:text-silver-tree-400 cursor-default"
            onClick={()=>setShowMisc(!showMisc)}
            >
            Misc
            </div>
            {showMiscComponent()}
            
          </div>
        </Layout>
      </main>
    </div>
  )
}
